# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# confirmations, etc.) must go above this block; everything else may go below.
# Initialization code that may require console input (password prompts, [y/n]
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# environment variables
export EDITOR='nvim'
export TERM='xterm-256color'
export ENVIRONMENT='development'
export GOPATH='/Users/byron/go'
export PATH=$PATH:$GOPATH/bin
export PATH=$PATH:$HOME/.local/bin:/opt/local/bin:opt/local/sbin

if [[ -f "/opt/homebrew/bin/brew" ]] then
  # If you're using macOS, you'll want this enabled
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Set the directory we want to store zinit and plugins
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download Zinit, if it's not there yet
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source/Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# Add in Powerlevel10k
zinit ice depth=1; zinit light romkatv/powerlevel10k

# Add in zsh plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab
zinit light hlissner/zsh-autopair
zinit light olets/zsh-abbr

# Add in snippets
zinit snippet OMZP::command-not-found
zinit snippet OMZP::colored-man-pages
zinit snippet OMZP::direnv
zinit snippet OMZP::docker-compose
zinit snippet OMZP::git
zinit snippet OMZP::golang
zinit snippet OMZP::grc
zinit snippet OMZP::sudo
zinit snippet OMZP::tmux

# Load completions
autoload -U compinit && compinit
zinit cdreplay -q

# Keybindings
bindkey -e
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey '^[w' kill-region

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'
zstyle ':fzf-tab:complete:__zoxide_z:*' fzf-preview 'ls --color $realpath'

# History
HISTSIZE=5000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Aliases
alias ls='eza'
alias l='eza'
alias ll="eza -l";
alias lh="eza -lah";
alias vim='nvim'
alias c='clear'
alias q='exit'
alias e='$EDITOR'
alias gs='git status -s';
alias cat='bat -p'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../../'
alias nvchad='NVIM_APPNAME=nvim-nvchad nvim';
alias nv='NVIM_APPNAME=nvim-nvchad nvim';
alias nvlazy='NVIM_APPNAME=nvim-lazyvim nvim';
alias nvl='NVIM_APPNAME=nvim-lazyvim nvim';
alias nvastro='NVIM_APPNAME=nvim-astro nvim';
alias nva='NVIM_APPNAME=nvim-astro nvim';
alias nvcustom='NVIM_APPNAME=nvim-custom nvim';
alias nvc='NVIM_APPNAME=nvim-custom nvim';
alias src='source ~/.zshrc';
alias zz='$EDITOR ~/.config/home-manager/zshrc';
alias zf='$EDITOR ~/.config/home-manager/nix-darwin/flake.nix';
alias hms='home-manager switch && source ~/.zshrc';
alias flk='nvim ~/.config/home-manager/nix-darwin/flake.nix';

# Shell integrations
eval "$(fzf --zsh)"
eval "$(zoxide init --cmd cd zsh)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
